# Generated by Django 3.2.6 on 2021-08-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaomaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matrix',
            new_name='map',
        ),
    ]
