# Generated by Django 3.2.6 on 2021-08-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaomaps', '0002_rename_matrix_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='data',
        ),
    ]
