# Generated by Django 3.2.6 on 2021-08-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaomaps', '0003_remove_map_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
