# Generated by Django 3.2.6 on 2021-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaomaps', '0004_map_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
