# Generated by Django 3.2.6 on 2021-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaomaps', '0009_auto_20210826_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='fillOpacity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='strokeOpacity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='strokeWeight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
