# Generated by Django 3.2.6 on 2021-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaomaps', '0010_auto_20210826_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
